/*
JORGE EDUARDO ESCOBAR BUGARINI - ISC - 21550317
 */
package com.views;

import com.controller.Controller;

/**
 *
 * @author user
 */
public class ClientesInactivos extends javax.swing.JPanel {

    /**
     * Creates new form ClientesActivos1
     */
      private Controller controller;

    public void setController(Controller controller) {
        this.controller = controller;
    }
    
    public ClientesInactivos() {
        initComponents();
        setSize(970, 548);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        goBackBtn = new javax.swing.JButton();
        tableContainer = new javax.swing.JScrollPane();
        tableInactive = new javax.swing.JTable();
        reactivarCliente = new javax.swing.JButton();
        lblReactivar = new javax.swing.JLabel();
        btnModifyCliente = new javax.swing.JButton();
        lblModify = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        banner.setBackground(new java.awt.Color(255, 0, 0));

        title.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Clientes inactivos");

        goBackBtn.setBackground(new java.awt.Color(255, 0, 0));
        goBackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/esquema-de-boton-circular-de-flecha-hacia-atras-izquierda.png"))); // NOI18N
        goBackBtn.setBorder(null);
        goBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(goBackBtn)
                .addGap(374, 374, 374)
                .addComponent(title)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(goBackBtn)
                    .addComponent(title))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        add(banner);
        banner.setBounds(0, 0, 970, 90);

        tableInactive.setBackground(new java.awt.Color(255, 255, 255));
        tableInactive.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        tableInactive.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tableInactive.setForeground(new java.awt.Color(0, 0, 0));
        tableInactive.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CLAVE", "CURP", "NOMBRE COMPLETO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableInactive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableInactive.setGridColor(new java.awt.Color(255, 0, 0));
        tableInactive.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tableContainer.setViewportView(tableInactive);

        add(tableContainer);
        tableContainer.setBounds(110, 110, 430, 410);

        reactivarCliente.setBackground(new java.awt.Color(255, 0, 0));
        reactivarCliente.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        reactivarCliente.setForeground(new java.awt.Color(255, 255, 255));
        reactivarCliente.setText("Reactivar cliente");
        reactivarCliente.setToolTipText("");
        reactivarCliente.setBorder(null);
        reactivarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(reactivarCliente);
        reactivarCliente.setBounds(720, 250, 133, 40);

        lblReactivar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/agregar-contacto.png"))); // NOI18N
        add(lblReactivar);
        lblReactivar.setBounds(760, 180, 64, 64);

        btnModifyCliente.setBackground(new java.awt.Color(255, 0, 0));
        btnModifyCliente.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnModifyCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnModifyCliente.setText("Modificar cliente");
        btnModifyCliente.setToolTipText("");
        btnModifyCliente.setBorder(null);
        btnModifyCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnModifyCliente);
        btnModifyCliente.setBounds(720, 390, 133, 40);

        lblModify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/modificar.png"))); // NOI18N
        add(lblModify);
        lblModify.setBounds(760, 320, 64, 64);
    }// </editor-fold>//GEN-END:initComponents

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
         controller.mostrarPrincipal();
      
    }//GEN-LAST:event_goBackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel banner;
    private javax.swing.JButton btnModifyCliente;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JLabel lblModify;
    private javax.swing.JLabel lblReactivar;
    private javax.swing.JButton reactivarCliente;
    public javax.swing.JScrollPane tableContainer;
    public javax.swing.JTable tableInactive;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
