/*
JORGE EDUARDO ESCOBAR BUGARINI - ISC - 21550317
 */
package com.views;

import com.controller.Controller;

/**
 *
 * @author user
 */
public class ClientesActivos extends javax.swing.JPanel {

    /**
     * Creates new form ClientesActivos1
     */
    private Controller controller;

    public void setController(Controller controller) {
        this.controller = controller;
    }

    public ClientesActivos() {
        initComponents();
        setSize(970, 548);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        goBackBtn = new javax.swing.JButton();
        ClientesScrollPane = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        removeClientBtn = new javax.swing.JButton();
        rmovLbl = new javax.swing.JLabel();
        modifyClientBtn = new javax.swing.JButton();
        modLb = new javax.swing.JLabel();
        accountsBtn = new javax.swing.JButton();
        accLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        banner.setBackground(new java.awt.Color(255, 0, 0));

        title.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Clientes activos");

        goBackBtn.setBackground(new java.awt.Color(255, 0, 0));
        goBackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/esquema-de-boton-circular-de-flecha-hacia-atras-izquierda.png"))); // NOI18N
        goBackBtn.setBorder(null);
        goBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(goBackBtn)
                .addGap(376, 376, 376)
                .addComponent(title)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goBackBtn)
                    .addComponent(title))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(banner);
        banner.setBounds(0, 0, 970, 90);

        TablaClientes.setBackground(new java.awt.Color(255, 255, 255));
        TablaClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        TablaClientes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TablaClientes.setForeground(new java.awt.Color(255, 255, 255));
        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CLAVE", "CURP", "NOMBRE COMPLETO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TablaClientes.setGridColor(new java.awt.Color(255, 0, 0));
        TablaClientes.setSelectionBackground(new java.awt.Color(255, 102, 102));
        ClientesScrollPane.setViewportView(TablaClientes);

        add(ClientesScrollPane);
        ClientesScrollPane.setBounds(20, 110, 640, 410);

        removeClientBtn.setBackground(new java.awt.Color(255, 0, 0));
        removeClientBtn.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        removeClientBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeClientBtn.setText("Dar de baja cliente");
        removeClientBtn.setToolTipText("");
        removeClientBtn.setBorder(null);
        removeClientBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(removeClientBtn);
        removeClientBtn.setBounds(760, 200, 133, 40);

        rmovLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rmovLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/eliminar-amigo.png"))); // NOI18N
        add(rmovLbl);
        rmovLbl.setBounds(800, 130, 64, 64);

        modifyClientBtn.setBackground(new java.awt.Color(255, 0, 0));
        modifyClientBtn.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        modifyClientBtn.setForeground(new java.awt.Color(255, 255, 255));
        modifyClientBtn.setText("Modificar cliente");
        modifyClientBtn.setToolTipText("");
        modifyClientBtn.setBorder(null);
        modifyClientBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(modifyClientBtn);
        modifyClientBtn.setBounds(760, 340, 133, 40);

        modLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/modificar.png"))); // NOI18N
        add(modLb);
        modLb.setBounds(800, 270, 64, 64);

        accountsBtn.setBackground(new java.awt.Color(255, 0, 0));
        accountsBtn.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        accountsBtn.setForeground(new java.awt.Color(255, 255, 255));
        accountsBtn.setText("Ver cuentas");
        accountsBtn.setToolTipText("");
        accountsBtn.setBorder(null);
        accountsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(accountsBtn);
        accountsBtn.setBounds(760, 470, 133, 40);

        accLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/cuentas-cliente.png"))); // NOI18N
        add(accLbl);
        accLbl.setBounds(800, 400, 64, 64);
    }// </editor-fold>//GEN-END:initComponents

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
        controller.mostrarPrincipal();

    }//GEN-LAST:event_goBackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ClientesScrollPane;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JLabel accLbl;
    private javax.swing.JButton accountsBtn;
    private javax.swing.JPanel banner;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JLabel modLb;
    private javax.swing.JButton modifyClientBtn;
    private javax.swing.JButton removeClientBtn;
    private javax.swing.JLabel rmovLbl;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
