/*
JORGE EDUARDO ESCOBAR BUGARINI - ISC - 21550317
 */
package com.views;

import com.controller.Controller;
import com.model.Cliente;
import com.model.Cuenta;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class CuentasCliente extends javax.swing.JPanel {

    /**
     * Creates new form CuentasCliente1
     */

       Cliente clienteActivo;
    
     private Controller controller;

     public void setController(Controller controller) {
         this.controller = controller;
     }
     

    public CuentasCliente() {
        initComponents();
        setSize(970, 548);
    }
    
    public void llenarTabla(Cliente cliente){
     clienteActivo = cliente;
    DefaultTableModel dt = (DefaultTableModel) tableCuentas.getModel();
        List<Cuenta> cuentas = controller.getLogicaCuenta().getListaCuentas(cliente); 
        
         int i=0;
        while(dt.getRowCount()!=cuentas.size()){
           
            dt.addRow(new Object[]{
                
                cuentas.get(i).getCliente().getCurp(),
                cuentas.get(i).getNumerocuenta()
            });
            System.out.println("Entro cuenta" +i);
            i++;
        }
        tableCuentas.setModel(dt);
    }
    
    public void limpiarTabla(){
        DefaultTableModel dt = (DefaultTableModel) tableCuentas.getModel();
        dt.setRowCount(0);
        tableCuentas.setModel(dt);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        goBackBtn = new javax.swing.JButton();
        tableContainer = new javax.swing.JScrollPane();
        tableCuentas = new javax.swing.JTable();
        addAccountBtn = new javax.swing.JButton();
        deleteAccBtn = new javax.swing.JButton();
        verTarjetasBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner.setBackground(new java.awt.Color(255, 0, 0));

        title.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Cuentas del cliente");

        goBackBtn.setBackground(new java.awt.Color(255, 0, 0));
        goBackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/esquema-de-boton-circular-de-flecha-hacia-atras-izquierda.png"))); // NOI18N
        goBackBtn.setBorder(null);
        goBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(goBackBtn)
                .addGap(359, 359, 359)
                .addComponent(title)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goBackBtn)
                    .addComponent(title))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 90));

        tableCuentas.setBackground(new java.awt.Color(255, 255, 255));
        tableCuentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        tableCuentas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tableCuentas.setForeground(new java.awt.Color(0, 0, 0));
        tableCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CURP", "NUMERO DE CUENTA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableCuentas.setGridColor(new java.awt.Color(255, 0, 0));
        tableCuentas.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tableContainer.setViewportView(tableCuentas);

        add(tableContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 430, 350));

        addAccountBtn.setBackground(new java.awt.Color(255, 0, 0));
        addAccountBtn.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        addAccountBtn.setForeground(new java.awt.Color(255, 255, 255));
        addAccountBtn.setText("Añadir cuenta");
        addAccountBtn.setToolTipText("");
        addAccountBtn.setBorder(null);
        addAccountBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountBtnActionPerformed(evt);
            }
        });
        add(addAccountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 133, 40));

        deleteAccBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteAccBtn.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        deleteAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteAccBtn.setText("Eliminar cuenta");
        deleteAccBtn.setToolTipText("");
        deleteAccBtn.setBorder(null);
        deleteAccBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(deleteAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 133, 40));

        verTarjetasBtn.setBackground(new java.awt.Color(255, 0, 0));
        verTarjetasBtn.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        verTarjetasBtn.setForeground(new java.awt.Color(255, 255, 255));
        verTarjetasBtn.setText("Ver tarjetas");
        verTarjetasBtn.setToolTipText("");
        verTarjetasBtn.setBorder(null);
        verTarjetasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(verTarjetasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 133, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
        controller.mostrarClientesActivos();
        limpiarTabla();
       
    }//GEN-LAST:event_goBackBtnActionPerformed

    private void addAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountBtnActionPerformed
        controller.mostrarRegistrarCuenta();
        
    }//GEN-LAST:event_addAccountBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAccountBtn;
    private javax.swing.JPanel banner;
    private javax.swing.JButton deleteAccBtn;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JScrollPane tableContainer;
    public javax.swing.JTable tableCuentas;
    private javax.swing.JLabel title;
    private javax.swing.JButton verTarjetasBtn;
    // End of variables declaration//GEN-END:variables
}
