/*
JORGE EDUARDO ESCOBAR BUGARINI - ISC - 21550317
 */
package com.views;

import com.controller.Controller;

/**
 *
 * @author user
 */
public class RegistrarCuenta extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarCuenta1
     */
    public RegistrarCuenta() {
        initComponents();
        setSize(970, 548);
    }
    
    private Controller controller;

    public void setController(Controller controller) {
        this.controller = controller;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        banner = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        goBackBtn = new javax.swing.JButton();
        Container = new javax.swing.JPanel();
        lblNumC = new javax.swing.JLabel();
        txtNumC = new javax.swing.JTextField();
        lblTasa = new javax.swing.JLabel();
        txtTasa = new javax.swing.JTextField();
        lblFechaPago = new javax.swing.JLabel();
        lblDiaPago = new javax.swing.JLabel();
        comboDiaPago = new javax.swing.JComboBox<>();
        lblMesPago = new javax.swing.JLabel();
        comboMesPago = new javax.swing.JComboBox<>();
        lblAñoPago = new javax.swing.JLabel();
        txtAñoPago = new javax.swing.JTextField();
        lblRegC = new javax.swing.JLabel();
        btnRegAcc = new javax.swing.JButton();
        lblFechaCorte = new javax.swing.JLabel();
        comboDiaCorte = new javax.swing.JComboBox<>();
        lblDiaCorte = new javax.swing.JLabel();
        lblMesCorte = new javax.swing.JLabel();
        comboMesCorte = new javax.swing.JComboBox<>();
        lblAñoCorte = new javax.swing.JLabel();
        txtAñoCorte = new javax.swing.JTextField();
        lblFechaCreacion = new javax.swing.JLabel();
        txtAñoCreacion = new javax.swing.JTextField();
        comboAñoCreacion = new javax.swing.JComboBox<>();
        comboDiaCreacion = new javax.swing.JComboBox<>();
        lblDiaCreacion = new javax.swing.JLabel();
        lblMesCreacion = new javax.swing.JLabel();
        lblAñoCreacion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        banner.setBackground(new java.awt.Color(255, 0, 0));

        title.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Registrar cuenta");

        goBackBtn.setBackground(new java.awt.Color(255, 0, 0));
        goBackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/esquema-de-boton-circular-de-flecha-hacia-atras-izquierda.png"))); // NOI18N
        goBackBtn.setBorder(null);

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(goBackBtn)
                .addGap(382, 382, 382)
                .addComponent(title)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(goBackBtn)
                    .addComponent(title))
                .addGap(21, 21, 21))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 391;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(banner, gridBagConstraints);

        Container.setBackground(new java.awt.Color(255, 255, 255));

        lblNumC.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblNumC.setForeground(new java.awt.Color(0, 0, 0));
        lblNumC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumC.setText("Número de cuenta");

        txtNumC.setBackground(new java.awt.Color(255, 255, 255));
        txtNumC.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNumC.setForeground(new java.awt.Color(0, 0, 0));
        txtNumC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        lblTasa.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblTasa.setForeground(new java.awt.Color(0, 0, 0));
        lblTasa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTasa.setText("Tasa de interés");

        txtTasa.setBackground(new java.awt.Color(255, 255, 255));
        txtTasa.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTasa.setForeground(new java.awt.Color(0, 0, 0));
        txtTasa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTasa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        lblFechaPago.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblFechaPago.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaPago.setText("Fecha de pago");

        lblDiaPago.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblDiaPago.setForeground(new java.awt.Color(0, 0, 0));
        lblDiaPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiaPago.setText("Día");

        comboDiaPago.setBackground(new java.awt.Color(255, 255, 255));
        comboDiaPago.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboDiaPago.setForeground(new java.awt.Color(0, 0, 0));
        comboDiaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comboDiaPago.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        comboDiaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiaPagoActionPerformed(evt);
            }
        });

        lblMesPago.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblMesPago.setForeground(new java.awt.Color(0, 0, 0));
        lblMesPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMesPago.setText("Mes");

        comboMesPago.setBackground(new java.awt.Color(255, 255, 255));
        comboMesPago.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboMesPago.setForeground(new java.awt.Color(0, 0, 0));
        comboMesPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        comboMesPago.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        comboMesPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesPagoActionPerformed(evt);
            }
        });

        lblAñoPago.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblAñoPago.setForeground(new java.awt.Color(0, 0, 0));
        lblAñoPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAñoPago.setText("Año");

        txtAñoPago.setBackground(new java.awt.Color(255, 255, 255));
        txtAñoPago.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtAñoPago.setForeground(new java.awt.Color(0, 0, 0));
        txtAñoPago.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        lblRegC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/cuenta.png"))); // NOI18N

        btnRegAcc.setBackground(new java.awt.Color(255, 0, 0));
        btnRegAcc.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnRegAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnRegAcc.setText("Registrar cuenta");
        btnRegAcc.setBorder(null);
        btnRegAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAccActionPerformed(evt);
            }
        });

        lblFechaCorte.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblFechaCorte.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaCorte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaCorte.setText("Fecha de corte");

        comboDiaCorte.setBackground(new java.awt.Color(255, 255, 255));
        comboDiaCorte.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboDiaCorte.setForeground(new java.awt.Color(0, 0, 0));
        comboDiaCorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comboDiaCorte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        comboDiaCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiaCorteActionPerformed(evt);
            }
        });

        lblDiaCorte.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblDiaCorte.setForeground(new java.awt.Color(0, 0, 0));
        lblDiaCorte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiaCorte.setText("Día");

        lblMesCorte.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblMesCorte.setForeground(new java.awt.Color(0, 0, 0));
        lblMesCorte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMesCorte.setText("Mes");

        comboMesCorte.setBackground(new java.awt.Color(255, 255, 255));
        comboMesCorte.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboMesCorte.setForeground(new java.awt.Color(0, 0, 0));
        comboMesCorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        comboMesCorte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        comboMesCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesCorteActionPerformed(evt);
            }
        });

        lblAñoCorte.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblAñoCorte.setForeground(new java.awt.Color(0, 0, 0));
        lblAñoCorte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAñoCorte.setText("Año");

        txtAñoCorte.setBackground(new java.awt.Color(255, 255, 255));
        txtAñoCorte.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtAñoCorte.setForeground(new java.awt.Color(0, 0, 0));
        txtAñoCorte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        lblFechaCreacion.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblFechaCreacion.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaCreacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaCreacion.setText("Fecha de creacion");

        txtAñoCreacion.setBackground(new java.awt.Color(255, 255, 255));
        txtAñoCreacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtAñoCreacion.setForeground(new java.awt.Color(0, 0, 0));
        txtAñoCreacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        comboAñoCreacion.setBackground(new java.awt.Color(255, 255, 255));
        comboAñoCreacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboAñoCreacion.setForeground(new java.awt.Color(0, 0, 0));
        comboAñoCreacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        comboAñoCreacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        comboAñoCreacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAñoCreacionActionPerformed(evt);
            }
        });

        comboDiaCreacion.setBackground(new java.awt.Color(255, 255, 255));
        comboDiaCreacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboDiaCreacion.setForeground(new java.awt.Color(0, 0, 0));
        comboDiaCreacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comboDiaCreacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        comboDiaCreacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiaCreacionActionPerformed(evt);
            }
        });

        lblDiaCreacion.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblDiaCreacion.setForeground(new java.awt.Color(0, 0, 0));
        lblDiaCreacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiaCreacion.setText("Día");

        lblMesCreacion.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblMesCreacion.setForeground(new java.awt.Color(0, 0, 0));
        lblMesCreacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMesCreacion.setText("Mes");

        lblAñoCreacion.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblAñoCreacion.setForeground(new java.awt.Color(0, 0, 0));
        lblAñoCreacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAñoCreacion.setText("Año");

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(lblFechaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblDiaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboDiaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMesPago, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMesPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAñoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAñoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addComponent(lblNumC, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addComponent(lblTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addComponent(lblFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                                .addComponent(lblRegC))))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerLayout.createSequentialGroup()
                                        .addGap(161, 161, 161)
                                        .addComponent(lblFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ContainerLayout.createSequentialGroup()
                                        .addComponent(lblDiaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboDiaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMesCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(comboAñoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblAñoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtAñoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addComponent(lblDiaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboDiaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMesCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboMesCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAñoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAñoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(86, 86, 86))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)))
                        .addGap(12, 12, 12)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDiaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMesPago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMesPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAñoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAñoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFechaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addComponent(lblRegC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDiaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMesCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMesCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAñoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAñoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDiaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMesCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAñoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAñoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAñoCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 163;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        add(Container, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setToolTipText("");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/8292057.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -7;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 730, 0, 0);
        add(jPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void comboDiaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDiaPagoActionPerformed

    private void comboMesPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMesPagoActionPerformed

    private void btnRegAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegAccActionPerformed

    private void comboDiaCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiaCorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDiaCorteActionPerformed

    private void comboMesCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesCorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMesCorteActionPerformed

    private void comboAñoCreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAñoCreacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAñoCreacionActionPerformed

    private void comboDiaCreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiaCreacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDiaCreacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel banner;
    private javax.swing.JButton btnRegAcc;
    private javax.swing.JComboBox<String> comboAñoCreacion;
    private javax.swing.JComboBox<String> comboDiaCorte;
    private javax.swing.JComboBox<String> comboDiaCreacion;
    private javax.swing.JComboBox<String> comboDiaPago;
    private javax.swing.JComboBox<String> comboMesCorte;
    private javax.swing.JComboBox<String> comboMesPago;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAñoCorte;
    private javax.swing.JLabel lblAñoCreacion;
    private javax.swing.JLabel lblAñoPago;
    private javax.swing.JLabel lblDiaCorte;
    private javax.swing.JLabel lblDiaCreacion;
    private javax.swing.JLabel lblDiaPago;
    private javax.swing.JLabel lblFechaCorte;
    private javax.swing.JLabel lblFechaCreacion;
    private javax.swing.JLabel lblFechaPago;
    private javax.swing.JLabel lblMesCorte;
    private javax.swing.JLabel lblMesCreacion;
    private javax.swing.JLabel lblMesPago;
    private javax.swing.JLabel lblNumC;
    private javax.swing.JLabel lblRegC;
    private javax.swing.JLabel lblTasa;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtAñoCorte;
    private javax.swing.JTextField txtAñoCreacion;
    private javax.swing.JTextField txtAñoPago;
    private javax.swing.JTextField txtNumC;
    private javax.swing.JTextField txtTasa;
    // End of variables declaration//GEN-END:variables
}
