/*
 * 
 * 
 */

/**
 *
 * @author Jorge Eduardo Escobar Bugarini -  ISC  - 21550317
 */

import LibreriaGraficos.*;

import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

public class VentanaSinRandom extends javax.swing.JFrame{

    /**
     * Creates new form VentanaSinRandom
     */
    int x,y;


    public VentanaSinRandom() {
        super("Ventana y figuras sin random");
        initComponents();
        JPaneDrawing.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                x=e.getX();
                y=e.getY();
            }

            @Override
            public void mousePressed(MouseEvent e) {
                
            }

            @Override
            public void mouseReleased(MouseEvent e) {
               
            }

            @Override
            public void mouseEntered(MouseEvent e) {
               
            }

            @Override
            public void mouseExited(MouseEvent e) {
             
            }
        });
    }
    
    
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPaneBtn = new javax.swing.JPanel();
        btnRectangulo = new javax.swing.JButton();
        btnCirculo = new javax.swing.JButton();
        btnTriangulo = new javax.swing.JButton();
        JPaneDrawing = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));

        JPaneBtn.setMaximumSize(new java.awt.Dimension(400, 100));
        JPaneBtn.setMinimumSize(new java.awt.Dimension(400, 100));

        btnRectangulo.setText("Rectangulo");
        btnRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanguloActionPerformed(evt);
            }
        });

        btnCirculo.setText("Circulo");
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        btnTriangulo.setText("Triangulo");
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPaneBtnLayout = new javax.swing.GroupLayout(JPaneBtn);
        JPaneBtn.setLayout(JPaneBtnLayout);
        JPaneBtnLayout.setHorizontalGroup(
            JPaneBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPaneBtnLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(btnRectangulo)
                .addGap(18, 18, 18)
                .addComponent(btnCirculo)
                .addGap(18, 18, 18)
                .addComponent(btnTriangulo)
                .addGap(66, 66, 66))
        );
        JPaneBtnLayout.setVerticalGroup(
            JPaneBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPaneBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPaneBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRectangulo)
                    .addComponent(btnCirculo)
                    .addComponent(btnTriangulo))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(JPaneBtn, java.awt.BorderLayout.NORTH);

        JPaneDrawing.setMaximumSize(new java.awt.Dimension(400, 300));
        JPaneDrawing.setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().add(JPaneDrawing, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanguloActionPerformed
        Rectangulo rect = new Rectangulo();
        rect.setSize(50,60);
        rect.setLocation(x,y);
        JPaneDrawing.add(rect);
        JPaneDrawing.repaint();
    }//GEN-LAST:event_btnRectanguloActionPerformed

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        Circulo circle = new Circulo();
        circle.setSize(50,50);
        circle.setLocation(x,y);
        JPaneDrawing.add(circle);
        JPaneDrawing.repaint();
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        Triangulo triangle = new Triangulo();
        triangle.setSize(50,50);
        triangle.setLocation(x,y);
        JPaneDrawing.add(triangle);
        JPaneDrawing.repaint();
    }//GEN-LAST:event_btnTrianguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSinRandom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPaneBtn;
    private javax.swing.JPanel JPaneDrawing;
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnRectangulo;
    private javax.swing.JButton btnTriangulo;
    // End of variables declaration//GEN-END:variables


    
}
